package com.example.backend.util.constant.notification;

public enum NotificationTypeEnum {
    BOOKING_CREATED,
    BOOKING_PENDING_CONFIRMATION,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    EQUIPMENT_BORROWED,
    EQUIPMENT_RETURNED,
    EQUIPMENT_LOST,
    EQUIPMENT_DAMAGED,
    PAYMENT_REQUESTED,
    PAYMENT_PROOF_UPLOADED,
    PAYMENT_CONFIRMED,
    MATCH_REMINDER,
    AI_KEY_EXPIRED
}
